In [2]:
import numpy as np

##Belajar tentang 1d & 2d Array

In [3]:
#1D array
a = np.array([3, 1, 5, 6])
print('banyaknya entry = ', a.size)
print('dimensi array = ', a.ndim)
print('ukuran array = ', a.shape)

banyaknya entry =  4
dimensi array =  1
ukuran array =  (4,)


In [4]:
#Slicing
a[1:]

array([1, 5, 6])

In [5]:
print('a[1:3] = ', a[1:3])
print('a[:3] = ', a[:3])

a[1:3] =  [1 5]
a[:3] =  [3 1 5]


In [6]:
#2D Array (Matriks)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##Latihan(2d Array)

In [7]:
#Lengkapi kodingan berikut
print('banyaknya entry = ', A.size )
print('dimensi array = ', A.ndim)
print('ukuran array = ', A.shape)

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3)


##Belajar Slicing

In [8]:
#Slicing
print('baris ke-2 = ', A[1])
print('entry ke-2 & 3 baris ke-2 = ', A[1, 1:])
print('entry pertama & 2 kolom ke-2 = ', A[:2, 1])

baris ke-2 =  [4 5 6]
entry ke-2 & 3 baris ke-2 =  [5 6]
entry pertama & 2 kolom ke-2 =  [2 5]


##Latihan (Slicing)

In [9]:
#Lengkapi kodingan berikut
print('baris ke-3 = ', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2, :2])
print('entry ke-2 & 3 kolom ke-3 = ', A[1:3, 2])

baris ke-3 =  [7 8 9]
entry ke-1 & 2 baris ke-3 =  [7 8]
entry ke-2 & 3 kolom ke-3 =  [6 9]


##Operasi Matematika

In [10]:
C = A*A
print('perkalian antar entry = ')
print(C)

perkalian antar entry = 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [11]:
print('perkalian matriks = ')
print(np.matmul(A,A))

perkalian matriks = 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [12]:
print('determinan matriks A = ', np.linalg.det(A))
print('determinan matriks C = ', np.linalg.det(C))

determinan matriks A =  0.0
determinan matriks C =  -216.00000000000006


In [13]:
print('nilai dan vektor eigen matriks A = ', np.linalg.eig(A))

nilai dan vektor eigen matriks A =  (array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [14]:
print('nilai eigen matriks A = ', np.linalg.eig(A)[0])

nilai eigen matriks A =  [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [15]:
print('vektor eigen matriks A = ', np.linalg.eig(A)[1])

vektor eigen matriks A =  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [16]:
e_vec = np.linalg.eig(A)[1][:, 0]
e_val = np.linalg.eig(A)[0][0]
e_value = e_val.real
print(np.matmul(A, e_vec))

[ -3.73863537  -8.46653421 -13.19443305]


In [17]:
print(e_val*e_vec)

[ -3.73863537  -8.46653421 -13.19443305]


##Latihan (operasi Matriks)

In [18]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

Hitunglah:

- 2*A
- 2+A
- A+B
- A-B
- determinan A
- invers dari B, simpan jadi matriks D
- transpose D
- nilai eigen dan vektor eigen dari A dan B

In [19]:
hasil1 = 2*A
hasil1

array([[ 2,  4],
       [14, 16]])

In [20]:
hasil2 = 2+A
hasil2

array([[ 3,  4],
       [ 9, 10]])

In [21]:
hasil3 = A+B
hasil3

array([[ 4,  7],
       [ 8, 14]])

In [22]:
hasil4 = A-B
hasil4

array([[-2, -3],
       [ 6,  2]])

In [33]:
#Ketik Kode disini
print("Array A: ")
print(A)
Determinant = np.linalg.det(A)
Determinant

Array A: 
[[1 2]
 [7 8]]


-6.0

In [35]:
#Ketik Kode disini
print("Array A: ")
print(B)
D = np.linalg.inv(B)
D

Array A: 
[[3 5]
 [1 6]]


array([[ 0.46153846, -0.38461538],
       [-0.07692308,  0.23076923]])

In [40]:
print(D)
print("")
#Transpose
print(D.T)

[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]

[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]


In [44]:
#Nilai Eigen Value & Vektor A
print("Array A: ""\n",A)
eigenvalue, eigenvektor= np.linalg.eig(A) #proses menjadi nilai eigen value dan vektor
print("\nEigenvalue")
print (eigenvalue)
print("\nEigenvektor")
print (eigenvektor)

Array A: 
 [[1 2]
 [7 8]]

Eigenvalue
[-0.62347538  9.62347538]

Eigenvektor
[[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]


In [46]:
#Nilai Eigen Value & Vektor B
print("Array B: ""\n",B)
eigenvalue, eigenvektor= np.linalg.eig(B) #proses menjadi nilai eigen value dan vektor
print("\nEigenvalue")
print (eigenvalue)
print("\nEigenvektor")
print (eigenvektor)

Array B: 
 [[3 5]
 [1 6]]

Eigenvalue
[1.8074176 7.1925824]

Eigenvektor
[[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?

Dapat dilihat dibawah, bawah perkalian antar entry itu perkalian tiap angka yang tempatnya sama, sedangkan perkalian matriks yaitu baris kali kolom

In [50]:
#Tunjukkan bedanya di kodingan di bawah ini
print(B)
print(D)
print(B*D)

[[3 5]
 [1 6]]
[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]
[[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]


In [49]:
print(np.matmul(B, D))

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


'1.22.3'

output jawaban:

perkalian entry = [[ 1.38461538, -1.92307692], [-0.07692308, 1.38461538]]

perkalian matriks = [[ 1.00000000e+00, -1.11022302e-16], [ 1.11022302e-16, 1.00000000e+00]]